## Ortec Case Study

In [ ]:
#IMPORTS
import pandas as pd
import numpy as np
from pathlib import Path

In [7]:
DATA = Path("DATA")

In [8]:
df = pd.read_csv(DATA / "ESG_Dataset.csv")

/var/folders/k_/0twp8_5j5790tr9j876ygj840000gn/T/ipykernel_32806/3689774604.py:1: DtypeWarning: Columns (0: DeckingType, 1: Kitchen, 2: DeckingExtras) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATA / "ESG_Dataset.csv")

In [9]:
df.head(20)

,ReservableOptionMarketGroupId,WeekBeforeArrival,WeekStartDate,MarketGroupCode,BrandGroupCode,CampsiteCode,AccoKindCode,AccoTypeRangeCode,SpecialPeriodCode,SeasonalCluster,...,DiscountedPrice,DiscountedPriceLastYear,HistoricalBookedNights,HistoricalBookedNightsLastYear,TotalBookedNights,Capacity,CapacityLastYear,latitude,longitude,AvgTemperature
0,Domestic-Thundurus-Meditite-Mobile-2024-01-01,52,2024-01-01,Domestic,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,1,0,20,234,0,35.2708,22.4478,12.0
1,DACH-Thundurus-Meditite-Mobile-2024-01-01,52,2024-01-01,DACH,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,2,0,63,234,0,35.2708,22.4478,12.0
2,Benelux-Thundurus-Meditite-Mobile-2024-01-01,52,2024-01-01,Benelux,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,0,0,32,234,0,35.2708,22.4478,12.0
3,Rest of Europe-Thundurus-Meditite-Mobile-2024-...,52,2024-01-01,Rest of Europe,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,0,0,17,234,0,35.2708,22.4478,12.0
4,Domestic-Thundurus-Meditite-Mobile-2024-01-01,51,2024-01-01,Domestic,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,0,0,20,234,0,35.2708,22.4478,12.0
5,DACH-Thundurus-Meditite-Mobile-2024-01-01,51,2024-01-01,DACH,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,3,0,63,234,0,35.2708,22.4478,12.0
6,Benelux-Thundurus-Meditite-Mobile-2024-01-01,51,2024-01-01,Benelux,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,1,0,32,234,0,35.2708,22.4478,12.0
7,Rest of Europe-Thundurus-Meditite-Mobile-2024-...,51,2024-01-01,Rest of Europe,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,0,0,17,234,0,35.2708,22.4478,12.0
8,Domestic-Thundurus-Meditite-Mobile-2024-01-01,50,2024-01-01,Domestic,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,0,0,20,234,0,35.2708,22.4478,12.0
9,DACH-Thundurus-Meditite-Mobile-2024-01-01,50,2024-01-01,DACH,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,2,0,63,234,0,35.2708,22.4478,12.0
10,Benelux-Thundurus-Meditite-Mobile-2024-01-01,50,2024-01-01,Benelux,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,1,0,32,234,0,35.2708,22.4478,12.0
11,Rest of Europe-Thundurus-Meditite-Mobile-2024-...,50,2024-01-01,Rest of Europe,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,0,0,17,234,0,35.2708,22.4478,12.0
12,Domestic-Thundurus-Meditite-Mobile-2024-01-01,49,2024-01-01,Domestic,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,0,0,20,234,0,35.2708,22.4478,12.0
13,DACH-Thundurus-Meditite-Mobile-2024-01-01,49,2024-01-01,DACH,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,2,0,63,234,0,35.2708,22.4478,12.0
14,Benelux-Thundurus-Meditite-Mobile-2024-01-01,49,2024-01-01,Benelux,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,2,0,32,234,0,35.2708,22.4478,12.0
15,Rest of Europe-Thundurus-Meditite-Mobile-2024-...,49,2024-01-01,Rest of Europe,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,1,0,17,234,0,35.2708,22.4478,12.0
16,Domestic-Thundurus-Meditite-Mobile-2024-01-01,48,2024-01-01,Domestic,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,0,0,20,234,0,35.2708,22.4478,12.0
17,DACH-Thundurus-Meditite-Mobile-2024-01-01,48,2024-01-01,DACH,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,2,0,63,234,0,35.2708,22.4478,12.0
18,Benelux-Thundurus-Meditite-Mobile-2024-01-01,48,2024-01-01,Benelux,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,1,0,32,234,0,35.2708,22.4478,12.0
19,Rest of Europe-Thundurus-Meditite-Mobile-2024-...,48,2024-01-01,Rest of Europe,Thundurus,Meditite,Mobile,Comfort,Festival of Arceus,Perrserker,...,145.38,0.0,1,0,17,234,0,35.2708,22.4478,12.0

In [12]:
df.describe()

,WeekBeforeArrival,Airco,Bedrooms,HotTub,Tropical,Bathrooms,Sleeps,TV,ArrivalMonth,DiscountedPrice,DiscountedPriceLastYear,HistoricalBookedNights,HistoricalBookedNightsLastYear,TotalBookedNights,Capacity,CapacityLastYear,latitude,longitude,AvgTemperature
count,3.130816e+06,3.130816e+06,3.130816e+06,3.130816e+06,3.130816e+06,3.130816e+06,3.130816e+06,3.130816e+06,3.130816e+06,3.130816e+06,3130816.0,3.130816e+06,3130816.0,3.130816e+06,3.130816e+06,3130816.0,3.130816e+06,3.130816e+06,3.130816e+06
mean,2.600000e+01,3.098592e-01,2.007042e+00,1.126761e-01,2.183099e-01,1.415493e+00,3.413310e+02,4.929577e-01,6.490385e+00,2.126906e+02,0.0,9.321742e-01,0.0,4.940523e+01,3.465669e+02,0.0,4.833767e+01,7.217771e+00,1.253713e+01
std,1.529706e+01,4.624354e-01,1.010484e+00,3.161964e-01,4.130989e-01,6.307046e-01,1.549068e+02,4.999505e-01,3.447394e+00,1.323063e+02,0.0,2.338494e+00,0.0,5.668432e+01,1.591119e+02,0.0,8.719626e+00,1.029888e+01,7.502503e+00
min,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.050000e+02,0.000000e+00,1.000000e+00,4.206000e+01,0.0,0.000000e+00,0.0,0.000000e+00,1.050000e+02,0.0,3.344880e+01,-6.975400e+00,-3.500000e+00
25%,1.300000e+01,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.210000e+02,0.000000e+00,3.750000e+00,1.071175e+02,0.0,0.000000e+00,0.0,8.000000e+00,2.280000e+02,0.0,4.073920e+01,-2.146300e+00,6.800000e+00
50%,2.600000e+01,0.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,3.205000e+02,0.000000e+00,6.500000e+00,1.843400e+02,0.0,0.000000e+00,0.0,3.100000e+01,3.240000e+02,0.0,4.809790e+01,5.509600e+00,1.250000e+01
75%,3.900000e+01,1.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,2.000000e+00,4.290000e+02,1.000000e+00,9.000000e+00,2.737900e+02,0.0,1.000000e+00,0.0,7.100000e+01,4.350000e+02,0.0,5.748670e+01,1.756240e+01,1.750000e+01
max,5.200000e+01,1.000000e+00,5.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,9.500000e+02,1.000000e+00,1.200000e+01,6.650600e+02,0.0,1.330000e+02,0.0,5.650000e+02,9.500000e+02,0.0,6.232910e+01,2.619230e+01,2.800000e+01

# Model choice

We want to optimize pricing, the only free variable we have, to maximize revenue, with capacity as the main constraint. We can derive features from the other columns.

We choose, initially, to use a multilevel model, because the data is hierarchically structured (campsites nested in regions in countries, crossed with markets), most groups have too little data to estimate elasticities independently, so the case explicitly requires a defensible cold-start procedure, and the pricing decision is per-group - partial pooling addresses all four simultaneously while delivering a posterior that drives the human in the loop story